<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function yplog_menu() {
  $items['yp/log'] = array(
    'title' => 'Reports',
    'description' => 'Index of available stream graphs.',
    'page callback' => 'yplog_graph_index',
    'access arguments' => array('access YP log'),
    'file' => 'yplog.graph.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['yp/log/%'] = array(
    'title' => 'Stream graph',
    'description' => 'Stream listenership graph.',
    'page callback' => 'yplog_graph_page',
    'page arguments' => array(2, 3),
    'access arguments' => array('access YP log'),
    'file' => 'yplog.graph.inc',
    'parent' => 'yp/log',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/services/yplog'] = array(
    'title' => 'YP log',
    'description' => 'Configure Icecast YP log settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yplog_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'yplog.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function yplog_perm() {
  return array('access YP log');
}

/**
 * Implementation of hook_cron().
 */
function yplog_cron() {
  // In the event that multiple streams have the same listen URL, they will be
  // summed together.
  db_query('INSERT INTO {yp_log} (listen_url, listeners, timestamp) SELECT listen_url, SUM(listeners), :timestamp FROM {yp_stream} GROUP BY listen_url', array(':timestamp' => REQUEST_TIME));
}

/**
 * Implementation of hook_theme().
 */
function yplog_theme() {
  return array(
    'yplog_graph' => array(
      'arguments' => array('listen_url' => '', 'filename' => ''),
      'file' => 'yplog.theme.inc',
      'template' => 'yplog-graph',
    ),
  );
}
