<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function yp_menu() {
  $items = array();
  $items['yp'] = array(
    'title' => 'Stream directory',
    'description' => 'Icecast stream directory.',
    'page callback' => 'yp_dir',
    'access arguments' => array('access content'),
    'file' => 'yp.dir.inc',
    'type' => MENU_SUGGESTED_ITEM,
  );
  $items['yp/dir'] = array(
    'title' => 'Directory',
    'description' => 'Icecast stream directory.',
    'page callback' => 'yp_dir',
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'yp.dir.inc',
  );
  $items['yp/cgi'] = array(
    'page callback' => 'yp_cgi',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'yp.cgi.inc',
  );
  $items['admin/settings/yp'] = array(
    'title' => 'YP directory',
    'description' => 'Configure YP directory settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yp_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'yp.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_block().
 */
function yp_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('YP directory'),
      'cache' => BLOCK_NO_CACHE,
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        $block = array(
          'subject' => t('Live radio directory'),
          'content' => theme('yp_dir'),
        );
        break;
    }
    return $block;
  }
}

/**
 * Implementation of hook_theme().
 */
function yp_theme() {
  return array(
    'yp_dir' => array(
      'arguments' => array(),
      'file' => 'yp.dir.inc',
    ),
  );
}

/**
 * Cleanup stale YP entries (not touched within past five minutes).
 */
function yp_cron() {
  db_query("DELETE FROM {yp_stream} WHERE %d - last_touch > %d", time(), 300);
}
